### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by jacklim2019** [pigoz/lat#12]
In https://github.com/pigoz/mpv-nihongo/issues/11#issuecomment-620401456 you mention that your active development is here (LAT), what does LAT do and how does it differs from https://github.com/pigoz/mpv-nihongo? Can it create anki card from mpv? How can I install this?

**Comment by pigoz** [comment]
Hi, sorry I've neglected this project for outside users. To be honest I've not yet thought about how to package it so that it's easy to use for other people. Ideally I'd like to reach a point where you can `gem install lat`, and if you have mecab and ffmpeg installed you are good to go. The long term objective is for it to be as easy as [anki-canvas](/pigoz/anki-canvas), but that's still a long way ahead.

Right now you would need to have installed:

- mpv master (the current stable release doesn't have the new scripting interface I use here)
- myougiden
- mecab
- ffmpeg

```
git clone git@github.com:pigoz/lat.git
cd lat
bundle install
ln -nfs bin/lat-mpv ~/.mpv/scripts/lat.run
```

There are a few outside dependencies I'd like to kill. The prime example is the dictionary: I want to create an internal dictionary using JMdict and maybe support for various 国語辞典, but I've yet to look into it.

As for improvements:
- Code is *much* better, and every part is test driven which makes adding new features easier
- Dictionary access is multithreaded
- Generated furigana matches the sigle Kanji, which results in a much nicer alignment. i.e.: `先[せん] 生[せい]` instead of `先生[せんせい]`. I have a very visual memory so this helped me immensely, and was the feature I could not add to mpv-nihongo since the code was so bad.
- You can also add stuff to Anki that comes from books (and the code uses TTS to create audio)

**Comment by jacklim2019** [comment]
Thanks for the instructions. I manage to install this and get everything working hence I'm closing this. Everything works fine and fulfill my need. Again, thank you very much.

**Comment by pigoz** [comment]
Stuff like Anki media collection path is hardcoded, so not nice :/

https://github.com/pigoz/lat/blob/master/lib/lat/anki.rb#L10

**Comment by jacklim2019** [comment]
True but once you got it working you save yourself a lot of time and make language learning more efficient

**Comment by pigoz** [comment]
> True but once you got it working you save yourself a lot of time and make language learning more efficient

If you could list the stuff you changed to get it work over at #4 it would be great for later reference.

**Comment by jacklim2019** [comment]
Sure but it might take a few days
